### ISSUE TITLE
Проблемы с запуском кода

### ISSUE THREAD

**Issue by manukyanst** [manukyanst/Checkers#1]
Исправить: не обрабатываются нажатия шашек
В новых функциях после исправления добавить документацию 
В следующий раз создавай отдельную ветку, и уже после просмотра делаем pull request

**Comment by NailKhas** [comment]
Окей, буду  искать ошибку

**Comment by NailKhas** [comment]
Все исправил, залил код в branch 1st version

**Comment by manukyanst** [comment]
Отлично, все работает
